api/urls.py
from django.urls import path

from api.views import MainPageList, PostDetailView, HotFeedsList, ExploreFeedsList, ReviewsCreateView


urlpatterns = [
    path('Newsline/', MainPageList.as_view()),
    path('Hot_feeds/', HotFeedsList.as_view()),
    path('Explore/', ExploreFeedsList.as_view()),
    path('post/<int:pk>/', PostDetailView.as_view()),
    path('reviews/create/', ReviewsCreateView.as_view()),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from error.views import page_not_found

urlpatterns = [
    path('', include('blog.urls')),
    path('newshub_admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.utils.translation import gettext_lazy as _
from users.models import Followers

User = get_user_model()

class UserCreationForm(UserCreationForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")


class FollowForm(forms.ModelForm):
    class Meta:
        model = Followers
        fields = ("follow_by",)

class ProfileSettingsForm(forms.ModelForm):
    bio = forms.CharField(label='О себе', widget=forms.Textarea(attrs={'rows': 3}), max_length=500, required=False)
    avatar = forms.ImageField(label='Аватар', required=False)
    background = forms.ImageField(label='Фоновое изображение', required=False)
    first_name = forms.CharField(label='Имя', max_length=30, required=True)

    class Meta:
        model = User
        fields = ['bio', 'avatar', 'background', 'first_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['bio'].initial = self.instance.bio
        self.fields['avatar'].initial = self.instance.avatar
        self.fields['background'].initial = self.instance.background
        self.fields['first_name'].initial = self.instance.first_name

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.bio = self.cleaned_data['bio']
        if self.cleaned_data['avatar']:
            user.avatar = self.cleaned_data['avatar']
        if self.cleaned_data['background']:
            user.background = self.cleaned_data['background']
        if commit:
            user.save()
        return user

templates/profile/settings.html
{% load static %}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="block_page settings_popup">
                <div class="popup_header d-flex justify-content-between align-items-center">
                    <h1>Edit profile</h1>
                    <button title="Close (Esc)" type="button" class="mfp-close close_button">×</button>
                </div>
                <form action="{% url 'profile_settings' %}" method="POST" enctype="multipart/form-data" id="popup-form">
                    {% csrf_token %}
                    <div class="profile_block">
                        <div class="profile_head d-flex header_margin">
                            <div class="avatar" id="choose_avatar">
                                {% if user.avatar %}
                                    <img src="{{ user.avatar.url }}" alt="" class="profile_img" id="avatar">
                                {% else %}
                                    <img src="{% static 'img/profile.png' %}" alt="" class="profile_img" id="avatar">
                                {% endif %}

                                <div class="choose_icon_block d-flex justify-content-center align-items-center">
                                    <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <rect width="40" height="40" rx="20" fill="#6C757D"/>
                                        <path d="M12 12H15L17 10H23L25 12H28C28.5304 12 29.0391 12.2107 29.4142 12.5858C29.7893 12.9609 30 13.4696 30 14V26C30 26.5304 29.7893 27.0391 29.4142 27.4142C29.0391 27.7893 28.5304 28 28 28H12C11.4696 28 10.9609 27.7893 10.5858 27.4142C10.2107 27.0391 10 26.5304 10 26V14C10 13.4696 10.2107 12.9609 10.5858 12.5858C10.9609 12.2107 11.4696 12 12 12ZM20 15C18.6739 15 17.4021 15.5268 16.4645 16.4645C15.5268 17.4021 15 18.6739 15 20C15 21.3261 15.5268 22.5979 16.4645 23.5355C17.4021 24.4732 18.6739 25 20 25C21.3261 25 22.5979 24.4732 23.5355 23.5355C24.4732 22.5979 25 21.3261 25 20C25 18.6739 24.4732 17.4021 23.5355 16.4645C22.5979 15.5268 21.3261 15 20 15ZM20 17C20.7956 17 21.5587 17.3161 22.1213 17.8787C22.6839 18.4413 23 19.2044 23 20C23 20.7956 22.6839 21.5587 22.1213 22.1213C21.5587 22.6839 20.7956 23 20 23C19.2044 23 18.4413 22.6839 17.8787 22.1213C17.3161 21.5587 17 20.7956 17 20C17 19.2044 17.3161 18.4413 17.8787 17.8787C18.4413 17.3161 19.2044 17 20 17Z" fill="white"/>
                                    </svg>
                                </div>

                            </div>

                            <div class="profile_info">
                                <div class="d-flex justify-content-end">
                                    <div class="btn btn-black settings_button" id="choose_bg">
                                        <p>Setup image</p>
                                    </div>
                                </div>
                                
                            </div>
                        </div> 
                        
                        {% if user.background %}
                            <div class="profile_bg d-flex justify-content-center align-items-center" style="background-position: center; background-size: cover; background-image: url({{ user.background.url }});" id="background_profile"> </div>
                        {% else %}
                            <div class="profile_bg d-flex justify-content-center align-items-center" id="background_profile"></div>
                        {% endif %}
                    </div>

                    <div class="settings_field">
                        <h2>Name</h2>
                        {{ form.first_name }}
                        {% if form.first_name.errors %}
                            <ul>
                            {% for error in form.first_name.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                    </div>

                    
                    <div class="settings_field">
                        <h2>Bio</h2>
                        <textarea id="textComment" name="bio" rows="3" placeholder="Text ( optional )">{{ form.bio.value }}</textarea>
                        {% if form.bio.errors %}
                            <ul>
                            {% for error in form.bio.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                    </div>

                    <input type="file" name="avatar" accept="image/*" id="id_avatar" style="display: none;">

                    <input type="file" name="background" accept="image/*" id="id_background" style="display: none;">

                    
                    <div class="settings_control d-flex justify-content-end align-items-center">
                        <button type="submit" class="btn btn-primary"><p>Save changes</p></button>
                    </div>
                    
                </form>
                    
            </div>
        </div>
    </div>
</div>
    
<script>

    let input = document.getElementById('id_avatar');
    let input_bg = document.getElementById('id_background');
    let chooseProfile = document.getElementById('choose_avatar');
    let chooseBg = document.getElementById('choose_bg');

    chooseProfile.addEventListener('click', function() {
        input.click();
    });

    chooseBg.addEventListener('click', function() {
        input_bg.click();
    });

    input.addEventListener('change', function(event) {
        let file = event.target.files[0];
        let reader = new FileReader();
        let img = document.getElementById('avatar');

        reader.onload = function(e) {
            img.src = e.target.result;
        };
        reader.readAsDataURL(file);
    });

    input_bg.addEventListener('change', function(event) {
        let file = event.target.files[0];
        let reader = new FileReader();
        let bg = document.getElementById('background_profile');

        reader.onload = function(e) {
            bg.style.backgroundImage = `url(${e.target.result})`;
        };
        reader.readAsDataURL(file);
    });

</script>